<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>mmd</string>
		</array>
		<key>name</key>
		<string>Mermaid</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#mermaid</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>mermaid</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>Architecture Diagram</string>
						<key>begin</key>
						<string>^\s*(architecture-beta)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(group|service)(group id)(icon name)?(title)(in)?(parent)?</string>
								<key>match</key>
								<string>(?i)\s*(group|service)\s+([\w-]+)\s*(\()?([\w\s-]+)?(:)?([\w\s-]+)?(\))?\s*(\[)?([\w\s-]+)?\s*(\])?\s*(in)?\s*([\w-]+)?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>7</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
									<key>8</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>9</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>10</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
									<key>11</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>12</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(service id)(group id)?:(T|B|L|R) &lt;?--&gt;? (T|B|L|R):(service id)(group id)?</string>
								<key>match</key>
								<string>(?i)\s*([\w-]+)\s*(\{)?\s*(group)?(\})?\s*(:)\s*(T|B|L|R)\s+(&lt;?--&gt;?)\s+(T|B|L|R)\s*(:)\s*([\w-]+)\s*(\{)?\s*(group)?(\})?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
									<key>7</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>8</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
									<key>9</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>10</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>11</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>12</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>13</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(junction)(junction id)(in)?(group)</string>
								<key>match</key>
								<string>(?i)\s*(junction)\s+([\w-]+)\s*(in)?\s*([\w-]+)?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Class Diagram</string>
						<key>begin</key>
						<string>^\s*(classDiagram)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(class name) ("multiplicity relationship")? (relationship) ("multiplicity relationship")? (class name) :? (labelText)?</string>
								<key>match</key>
								<string>(?i)([\w-]+)\s("(?:\d+|\*|0..\d+|1..\d+|1..\*)")?\s?(--o|--\*|\&lt;--|--\&gt;|&lt;\.\.|\.\.\&gt;|\&lt;\|\.\.|\.\.\|\&gt;|\&lt;\|--|--\|&gt;|--\*|--|\.\.|\*--|o--)\s("(?:\d+|\*|0..\d+|1..\d+|1..\*)")?\s?([\w-]+)\s?(:)?\s(.*)$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>entity.name.type.class.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>entity.name.type.class.mermaid</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>7</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(class name) : (visibility)?(function)( (function param/generic param)? )(classifier)? (return/generic return)?$</string>
								<key>match</key>
								<string>(?i)([\w-]+)\s?(:)\s([\+~#-])?([\w-]+)(\()([\w-]+)?(~)?([\w-]+)?(~)?\s?([\w-]+)?(\))([*\$]{0,2})\s?([\w-]+)?(~)?([\w-]+)?(~)?$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>entity.name.type.class.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>punctuation.parenthesis.open.mermaid</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>7</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>8</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>9</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
									<key>10</key>
									<dict>
										<key>name</key>
										<string>entity.name.variable.parameter.mermaid</string>
									</dict>
									<key>11</key>
									<dict>
										<key>name</key>
										<string>punctuation.parenthesis.closed.mermaid</string>
									</dict>
									<key>12</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>13</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>14</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>15</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>16</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(class name) : (visibility)?(datatype/generic data type) (attribute name)$</string>
								<key>match</key>
								<string>(?i)([\w-]+)\s?(:)\s([\+~#-])?([\w-]+)(~)?([\w-]+)?(~)?\s([\w-]+)?$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>entity.name.type.class.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>7</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
									<key>8</key>
									<dict>
										<key>name</key>
										<string>entity.name.variable.field.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>&lt;&lt;(Annotation)&gt;&gt; (class name)</string>
								<key>match</key>
								<string>(?i)(&lt;&lt;)([\w-]+)(&gt;&gt;)\s?([\w-]+)?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>entity.name.type.class.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>class (class name) ~?(generic type)?~? ({)</string>
								<key>begin</key>
								<string>(?i)(class)\s+([\w-]+)(~)?([\w-]+)?(~)?\s?({)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.type.class.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>match</key>
										<string>\%%.*</string>
										<key>name</key>
										<string>comment</string>
									</dict>
									<dict>
										<key>comment</key>
										<string>(visibility)?(function)( (function param/generic param)? )(classifier)? (return/generic return)?$</string>
										<key>begin</key>
										<string>(?i)\s([\+~#-])?([\w-]+)(\()</string>
										<key>beginCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>entity.name.function.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>punctuation.parenthesis.open.mermaid</string>
											</dict>
										</dict>
										<key>patterns</key>
										<array>
											<dict>
												<key>comment</key>
												<string>(TBD)</string>
												<key>match</key>
												<string>(?i)\s*,?\s*([\w-]+)?(~)?([\w-]+)?(~)?\s?([\w-]+)?</string>
												<key>captures</key>
												<dict>
													<key>1</key>
													<dict>
														<key>name</key>
														<string>storage.type.mermaid</string>
													</dict>
													<key>2</key>
													<dict>
														<key>name</key>
														<string>punctuation.definition.typeparameters.begin.mermaid</string>
													</dict>
													<key>3</key>
													<dict>
														<key>name</key>
														<string>storage.type.mermaid</string>
													</dict>
													<key>4</key>
													<dict>
														<key>name</key>
														<string>punctuation.definition.typeparameters.end.mermaid</string>
													</dict>
													<key>5</key>
													<dict>
														<key>name</key>
														<string>entity.name.variable.parameter.mermaid</string>
													</dict>
												</dict>
											</dict>
										</array>
										<key>end</key>
										<string>(?i)(\))([*\$]{0,2})\s?([\w-]+)?(~)?([\w-]+)?(~)?$</string>
										<key>endCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>punctuation.parenthesis.closed.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>storage.type.mermaid</string>
											</dict>
											<key>4</key>
											<dict>
												<key>name</key>
												<string>punctuation.definition.typeparameters.begin.mermaid</string>
											</dict>
											<key>5</key>
											<dict>
												<key>name</key>
												<string>storage.type.mermaid</string>
											</dict>
											<key>6</key>
											<dict>
												<key>name</key>
												<string>punctuation.definition.typeparameters.end.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(visibility)?(datatype/generic data type) (attribute name)$</string>
										<key>match</key>
										<string>(?i)\s([\+~#-])?([\w-]+)(~)?([\w-]+)?(~)?\s([\w-]+)?$</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>storage.type.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>punctuation.definition.typeparameters.begin.mermaid</string>
											</dict>
											<key>4</key>
											<dict>
												<key>name</key>
												<string>storage.type.mermaid</string>
											</dict>
											<key>5</key>
											<dict>
												<key>name</key>
												<string>punctuation.definition.typeparameters.end.mermaid</string>
											</dict>
											<key>6</key>
											<dict>
												<key>name</key>
												<string>entity.name.variable.field.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>&lt;&lt;(Annotation)&gt;&gt; (class name)</string>
										<key>match</key>
										<string>(?i)(&lt;&lt;)([\w-]+)(&gt;&gt;)\s?([\w-]+)?</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>punctuation.definition.typeparameters.begin.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>storage.type.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>punctuation.definition.typeparameters.end.mermaid</string>
											</dict>
											<key>4</key>
											<dict>
												<key>name</key>
												<string>entity.name.type.class.mermaid</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>(})</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>class (class name) ~?(generic type)?~?</string>
								<key>match</key>
								<string>(?i)(class)\s+([\w-]+)(~)?([\w-]+)?(~)?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.type.class.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.begin.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>storage.type.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>punctuation.definition.typeparameters.end.mermaid</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Entity Relationship Diagram</string>
						<key>begin</key>
						<string>^\s*(erDiagram)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(entity)</string>
								<key>match</key>
								<string>(?i)^\s*([\w-]+)\s*(\[)?\s*((?:[\w-]+)|(?:"[\w\s-]+"))?\s*(\])?$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(entity) {</string>
								<key>begin</key>
								<string>(?i)\s+([\w-]+)\s*(\[)?\s*((?:[\w-]+)|(?:"[\w\s-]+"))?\s*(\])?\s*({)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(type) (name) (PK|FK)? ("comment")?</string>
										<key>match</key>
										<string>(?i)\s*([\w-]+)\s+([\w-]+)\s+(PK|FK)?\s*("["\($&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*")?\s*</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>storage.type.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>4</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>match</key>
										<string>\%%.*</string>
										<key>name</key>
										<string>comment</string>
									</dict>
								</array>
								<key>end</key>
								<string>(})</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(entity) (relationship) (entity) : (label)</string>
								<key>match</key>
								<string>(?i)\s*([\w-]+)\s*((?:\|o|\|\||}o|}\||one or (?:zero|more|many)|zero or (?:one|more|many)|many\((?:0|1)\)|only one|0\+|1\+?)(?:..|--)(?:o\||\|\||o{|\|{|one or (?:zero|more|many)|zero or (?:one|more|many)|many\((?:0|1)\)|only one|0\+|1\+?))\s*([\w-]+)\s*(:)\s*((?:"[\w\s]*")|(?:[\w-]+))</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Gantt Diagram</string>
						<key>begin</key>
						<string>^\s*(gantt)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(dateFormat)\s+([\w\-\.]+)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(axisFormat)\s+([\w\%\/\\\-\.]+)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)(tickInterval)\s+(([1-9][0-9]*)(millisecond|second|minute|hour|day|week|month))</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(title)\s+(\s*["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(excludes)\s+((?:[\d\-,\s]+|monday|tuesday|wednesday|thursday|friday|saturday|sunday|weekends)+)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s+(todayMarker)\s+(.*)$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(section)\s+(\s*["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>begin</key>
								<string>(?i)^\s(.*)(:)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>match</key>
										<string>(crit|done|active|after)</string>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
									<dict>
										<key>match</key>
										<string>\%%.*</string>
										<key>name</key>
										<string>comment</string>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Git Graph</string>
						<key>begin</key>
						<string>^\s*(gitGraph)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>commit</string>
								<key>begin</key>
								<string>(?i)^\s*(commit)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(id)(:) ("id")</string>
										<key>match</key>
										<string>(?i)\s*(id)(:)\s?("[^"\n]*")</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(type)(:) (COMMIT_TYPE)</string>
										<key>match</key>
										<string>(?i)\s*(type)(:)\s?(NORMAL|REVERSE|HIGHLIGHT)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>entity.name.function.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(tag)(:) ("tag")</string>
										<key>match</key>
										<string>(?i)\s*(tag)(:)\s?("[\($&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*")</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(checkout) (branch-name)</string>
								<key>match</key>
								<string>(?i)^\s*(checkout)\s*([^\s"]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(branch) (branch-name) (order)?(:) (number)</string>
								<key>match</key>
								<string>(?i)^\s*(branch)\s*([^\s"]*)\s*(?:(order)(:)\s?(\d+))?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>constant.numeric.decimal.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(merge) (branch-name) (tag: "tag-name")?</string>
								<key>match</key>
								<string>(?i)^\s*(merge)\s*([^\s"]*)\s*(?:(tag)(:)\s?("[^"\n]*"))?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(cherry-pick) (id)(:)("commit-id")</string>
								<key>match</key>
								<string>(?i)^\s*(cherry-pick)\s+(id)(:)\s*("[^"\n]*")</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Graph</string>
						<key>begin</key>
						<string>^\s*(graph|flowchart)\s+([\p{Letter}\ 0-9]+)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>entity.name.function.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string/>
								<key>match</key>
								<string>(?i)^\s*(subgraph)\s+(\w+)(\[)("?[\w\s*+%=\\/:\.\-'`,&amp;^#$!?&lt;&gt;]*"?)(\])</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>^\s*(subgraph)\s+([\p{Letter}\ 0-9&lt;&gt;]+)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>^(?i)\s*(direction)\s+(RB|BT|RL|TD|LR)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>match</key>
								<string>\b(end)\b</string>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Entity)(Edge/Shape)(Text)(Edge/Shape)</string>
								<key>begin</key>
								<string>(?i)(\b(?:(?!--|==)[-\w])+\b\s*)(\(\[|\[\[|\[\(|\[|\(+|\&gt;|\{|\(\()</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>("multi-line text")</string>
										<key>begin</key>
										<string>\s*(")</string>
										<key>beginCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
										<key>patterns</key>
										<array>
											<dict>
												<key>comment</key>
												<string>capture inner text between quotes</string>
												<key>begin</key>
												<string>(?i)([^"]*)</string>
												<key>beginCaptures</key>
												<dict>
													<key>1</key>
													<dict>
														<key>name</key>
														<string>string</string>
													</dict>
												</dict>
												<key>patterns</key>
												<array>
													<dict>
														<key>match</key>
														<string>([^"]*)</string>
														<key>captures</key>
														<dict>
															<key>1</key>
															<dict>
																<key>name</key>
																<string>comment</string>
															</dict>
														</dict>
													</dict>
												</array>
												<key>end</key>
												<string>(?=")</string>
											</dict>
										</array>
										<key>end</key>
										<string>(")</string>
										<key>endCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(single line text)</string>
										<key>match</key>
										<string>(?i)\s*([$&amp;%\^/#.,?!;:*+&lt;&gt;_\'\\\w\s]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>(?i)(\]\)|\]\]|\)\]|\]|\)+|\}|\)\))</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Graph Link)("Multiline text")(Graph Link)</string>
								<key>begin</key>
								<string>(?i)\s*((?:-{2,5}|={2,5})[xo&gt;]?\|)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>("multi-line text")</string>
										<key>begin</key>
										<string>\s*(")</string>
										<key>beginCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
										<key>patterns</key>
										<array>
											<dict>
												<key>comment</key>
												<string>capture inner text between quotes</string>
												<key>begin</key>
												<string>(?i)([^"]*)</string>
												<key>beginCaptures</key>
												<dict>
													<key>1</key>
													<dict>
														<key>name</key>
														<string>string</string>
													</dict>
												</dict>
												<key>patterns</key>
												<array>
													<dict>
														<key>match</key>
														<string>([^"]*)</string>
														<key>captures</key>
														<dict>
															<key>1</key>
															<dict>
																<key>name</key>
																<string>comment</string>
															</dict>
														</dict>
													</dict>
												</array>
												<key>end</key>
												<string>(?=")</string>
											</dict>
										</array>
										<key>end</key>
										<string>(")</string>
										<key>endCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(single line text)</string>
										<key>match</key>
										<string>(?i)\s*([$&amp;%\^/#.,?!;:*+&lt;&gt;_\'\\\w\s]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>(?i)(\|)</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Graph Link Start Arrow)(Text)(Graph Link End Arrow)</string>
								<key>match</key>
								<string>(?i)\s*([xo&lt;]?(?:-{2,5}|={2,5}|-\.{1,3}|-\.))((?:(?!--|==)[\w\s*+%=\\/:\.\-'`,"&amp;^#$!?&lt;&gt;\[\]])*)((?:-{2,5}|={2,5}|\.{1,3}-|\.-)[xo&gt;]?)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Graph Link)</string>
								<key>match</key>
								<string>(?i)\s*([ox&lt;]?(?:-.{1,3}-|-{1,3}|={1,3})[ox&gt;]?)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>Entity</string>
								<key>match</key>
								<string>(\b(?:(?!--|==)[-\w])+\b\s*)</string>
								<key>name</key>
								<string>variable</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Class)(Node(s))(ClassName)</string>
								<key>match</key>
								<string>(?i)\s*(class)\s+(\b[-,\w]+)\s+(\b\w+\b)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(ClassDef)(ClassName)(Styles)</string>
								<key>match</key>
								<string>(?i)\s*(classDef)\s+(\b\w+\b)\s+(\b[-,:;#\w]+)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Click)(Entity)(Link)?(Tooltip)</string>
								<key>match</key>
								<string>(?i)\s*(click)\s+(\b[-\w]+\b\s*)(\b\w+\b)?\s("*.*")</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Pie Chart</string>
						<key>begin</key>
						<string>^\s*(pie)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(title)\s+(\s*["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>begin</key>
								<string>(?i)\s(.*)(:)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>match</key>
										<string>\%%.*</string>
										<key>name</key>
										<string>comment</string>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Quadrant Chart</string>
						<key>begin</key>
						<string>^\s*(quadrantChart)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(title)\s*(["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(x|y-axis) (text) (--&gt;)? (text)?</string>
								<key>begin</key>
								<string>(?i)^\s*([xy]-axis)\s+((?:(?!--&gt;)[$&amp;%/#.,?!*+=\'\\\-\w\s])*)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(--&gt;) (text)</string>
										<key>match</key>
										<string>(?i)\s*(--&gt;)\s*([$&amp;%/#.,?!*+=\'\\\-\w\s]*)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(quadrant-[1234])\s*(["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(text)(:) ([)(decimal)(,) (decimal)(])</string>
								<key>match</key>
								<string>(?i)\s*([$&amp;%/#.,?!*+=\'\\\-\w\s]*)\s*(:)\s*(\[)\s*(\d\.\d+)\s*(,)\s*(\d\.\d+)\s*(\])</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>constant.numeric.decimal.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>constant.numeric.decimal.mermaid</string>
									</dict>
									<key>7</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Requirement Diagram</string>
						<key>begin</key>
						<string>^\s*(requirementDiagram)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(requirement) (name) ({)</string>
								<key>begin</key>
								<string>(?i)^\s*((?:functional|interface|performance|physical)?requirement|designConstraint)\s*(["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)\s*({)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(id:) (variable id)</string>
										<key>match</key>
										<string>(?i)\s*(id:)\s*([$&amp;%\^/#.,?!;:*+&lt;&gt;_\'\\\w\s]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(text:) (text string)</string>
										<key>match</key>
										<string>(?i)\s*(text:)\s*([$&amp;%\^/#.,?!;:*+&lt;&gt;_\'\\\w\s]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(risk:) (risk option)</string>
										<key>match</key>
										<string>(?i)\s*(risk:)\s*(low|medium|high)\s*$</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>entity.name.function.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(verifyMethod)(:) (method)</string>
										<key>match</key>
										<string>(?i)\s*(verifymethod:)\s*(analysis|inspection|test|demonstration)\s*$</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>entity.name.function.mermaid</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>(?i)\s*(})</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(element) (name) ({)</string>
								<key>begin</key>
								<string>(?i)^\s*(element)\s*(["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)\s*({)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(type:) (user type)</string>
										<key>match</key>
										<string>(?i)\s*(type:)\s*(["$&amp;%\^/#.,?!;:*+&lt;&gt;_\'\\\w\s]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(docref:) (user ref)</string>
										<key>match</key>
										<string>(?i)\s*(docref:)\s*([$&amp;%\^/#.,?!;:*+&lt;&gt;_\'\\\w\s]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>(?i)\s*(})</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(source) (-) (type) (-&gt;) (destination)</string>
								<key>match</key>
								<string>(?i)^\s*([\w]+)\s*(-)\s*(contains|copies|derives|satisfies|verifies|refines|traces)\s*(-&gt;)\s*([\w]+)\s*$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(destination) (&lt;-) (type) (-) (source)</string>
								<key>match</key>
								<string>(?i)^\s*([\w]+)\s*(&lt;-)\s*(contains|copies|derives|satisfies|verifies|refines|traces)\s*(-)\s*([\w]+)\s*$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Sequence Diagram</string>
						<key>begin</key>
						<string>^\s*(sequenceDiagram)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>(\%%|#).*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(title)(title text)</string>
								<key>match</key>
								<string>(?i)(title)\s*(:)?\s+(\s*["\(\)$&amp;%\^/#.,?!:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(participant)(Actor)(as)?(Label)?</string>
								<key>match</key>
								<string>(?i)\s*(participant|actor)\s+((?:(?! as )["\(\)$&amp;%\^/#.?!*=&lt;&gt;\'\\\w\s])+)\s*(as)?\s(["\(\)$&amp;%\^/#.,?!*=&lt;&gt;\'\\\w\s]+)?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(activate/deactivate)(Actor)</string>
								<key>match</key>
								<string>(?i)\s*((?:de)?activate)\s+(\b["()$&amp;%^/#.?!*=&lt;&gt;'\\\w\s]+\b\)?\s*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Note)(direction)(Actor)(,)?(Actor)?(:)(Message)</string>
								<key>match</key>
								<string>(?i)\s*(Note)\s+((?:left|right)\sof|over)\s+(\b["()$&amp;%^/#.?!*=&lt;&gt;'\\\w\s]+\b\)?\s*)(,)?(\b["()$&amp;%^/#.?!*=&lt;&gt;'\\\w\s]+\b\)?\s*)?(:)(?:\s+([^;#]*))?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>6</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>7</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(loop)(loop text)</string>
								<key>match</key>
								<string>(?i)\s*(loop)(?:\s+([^;#]*))?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(end)</string>
								<key>match</key>
								<string>\s*(end)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(alt/else/option/par/and/autonumber/critical/opt)(text)</string>
								<key>match</key>
								<string>(?i)\s*(alt|else|option|par|and|rect|autonumber|critical|opt)(?:\s+([^#;]*))?$</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(Actor)(Arrow)(Actor)(:)(Message)</string>
								<key>match</key>
								<string>(?i)\s*(\b["()$&amp;%^/#.?!*=&lt;&gt;'\\\w\s]+\b\)?)\s*(-?-(?:\&gt;|x|\))\&gt;?[+-]?)\s*(["()$&amp;%^/#.?!*=&lt;&gt;'\\\w\s]+\b\)?)\s*(:)\s*([^;#]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(box transparent text)</string>
								<key>match</key>
								<string>(?i)\s*(box)\s+(transparent)(?:\s+([^;#]*))?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>entity.name.function.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(box text)</string>
								<key>match</key>
								<string>(?i)\s*(box)(?:\s+([^;#]*))?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>State Diagram</string>
						<key>begin</key>
						<string>^\s*(stateDiagram(?:-v2)?)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>}</string>
								<key>match</key>
								<string>\s+(})\s+</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>--</string>
								<key>match</key>
								<string>\s+(--)\s+</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(state)</string>
								<key>match</key>
								<string>^\s*([\w-]+)$</string>
								<key>name</key>
								<string>variable</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(state) : (description)</string>
								<key>match</key>
								<string>(?i)([\w-]+)\s+(:)\s+(\s*[-\w\s]+\b)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>state</string>
								<key>begin</key>
								<string>(?i)^\s*(state)\s+</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>"(description)" as (state)</string>
										<key>match</key>
										<string>(?i)\s*("[-\w\s]+\b")\s+(as)\s+([\w-]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(state name) {</string>
										<key>match</key>
										<string>(?i)\s*([\w-]+)\s+({)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(state name) &lt;&lt;fork|join&gt;&gt;</string>
										<key>match</key>
										<string>(?i)\s*([\w-]+)\s+(&lt;&lt;(?:fork|join)&gt;&gt;)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(state) --&gt;</string>
								<key>begin</key>
								<string>(?i)([\w-]+)\s+(--&gt;)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(state) (:)? (transition text)?</string>
										<key>match</key>
										<string>(?i)\s+([\w-]+)\s*(:)?\s*([^\n:]+)?</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>[*] (:)? (transition text)?</string>
										<key>match</key>
										<string>(?i)(\[\*\])\s*(:)?\s*([^\n:]+)?</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>[*] --&gt; (state) (:)? (transition text)?</string>
								<key>match</key>
								<string>(?i)(\[\*\])\s+(--&gt;)\s+([\w-]+)\s*(:)?\s*([^\n:]+)?</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>5</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>note left|right of (state name)</string>
								<key>match</key>
								<string>(?i)^\s*(note (?:left|right) of)\s+([\w-]+)\s+(:)\s*([^\n:]+)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>note left|right of (state name) (note text) end note</string>
								<key>begin</key>
								<string>(?i)^\s*(note (?:left|right) of)\s+([\w-]+)(.|\n)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>variable</string>
									</dict>
								</dict>
								<key>contentName</key>
								<string>string</string>
								<key>end</key>
								<string>(?i)(end note)</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>User Journey</string>
						<key>begin</key>
						<string>^\s*(journey)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(title|section)\s+(\s*["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>begin</key>
								<string>(?i)\s*(["\(\)$&amp;%\^/.,?!*+=&lt;&gt;\'\\\-\w\s]*)\s*(:)\s*(\d+)\s*(:)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>3</key>
									<dict>
										<key>name</key>
										<string>constant.numeric.decimal.mermaid</string>
									</dict>
									<key>4</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(taskName)</string>
										<key>match</key>
										<string>(?i)\s*,?\s*([^,#\n]+)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>variable</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>XY Chart</string>
						<key>begin</key>
						<string>^\s*(xychart(?:-beta)?(?:\s+horizontal)?)</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.mermaid</string>
							</dict>
						</dict>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\%%.*</string>
								<key>name</key>
								<string>comment</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?i)^\s*(title)\s+(\s*["\(\)$&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*)</string>
								<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>string</string>
									</dict>
								</dict>
							</dict>
							<dict>
								<key>comment</key>
								<string>(x-axis)</string>
								<key>begin</key>
								<string>(?i)^\s*(x-axis)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(decimal) (--&gt;) (decimal)</string>
										<key>match</key>
										<string>(?i)\s*([-+]?\d+\.?\d*)\s*(--&gt;)\s*([-+]?\d+\.?\d*)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>constant.numeric.decimal.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>constant.numeric.decimal.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>("text")</string>
										<key>match</key>
										<string>(?i)\s+("[\($&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*")</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(text)</string>
										<key>match</key>
										<string>(?i)\s+([\($&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w]*)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>([)(text)(,)(text)*(])</string>
										<key>begin</key>
										<string>\s*(\[)</string>
										<key>beginCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
										</dict>
										<key>patterns</key>
										<array>
											<dict>
												<key>comment</key>
												<string>(decimal)</string>
												<key>match</key>
												<string>(?i)\s*([-+]?\d+\.?\d*)</string>
												<key>captures</key>
												<dict>
													<key>1</key>
													<dict>
														<key>name</key>
														<string>constant.numeric.decimal.mermaid</string>
													</dict>
												</dict>
											</dict>
											<dict>
												<key>comment</key>
												<string>("text")</string>
												<key>match</key>
												<string>(?i)\s*("[\($&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*")</string>
												<key>captures</key>
												<dict>
													<key>1</key>
													<dict>
														<key>name</key>
														<string>string</string>
													</dict>
												</dict>
											</dict>
											<dict>
												<key>comment</key>
												<string>(text)</string>
												<key>match</key>
												<string>(?i)\s*([\($&amp;%\^/#.?!;:*+=&lt;&gt;\'\\\-\w\s]+)</string>
												<key>captures</key>
												<dict>
													<key>1</key>
													<dict>
														<key>name</key>
														<string>string</string>
													</dict>
												</dict>
											</dict>
											<dict>
												<key>comment</key>
												<string>(,)</string>
												<key>match</key>
												<string>(?i)\s*(,)</string>
												<key>captures</key>
												<dict>
													<key>1</key>
													<dict>
														<key>name</key>
														<string>keyword.control.mermaid</string>
													</dict>
												</dict>
											</dict>
										</array>
										<key>end</key>
										<string>\s*(\])</string>
										<key>endCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(y-axis)</string>
								<key>begin</key>
								<string>(?i)^\s*(y-axis)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(decimal) (--&gt;) (decimal)</string>
										<key>match</key>
										<string>(?i)\s*([-+]?\d+\.?\d*)\s*(--&gt;)\s*([-+]?\d+\.?\d*)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>constant.numeric.decimal.mermaid</string>
											</dict>
											<key>2</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
											<key>3</key>
											<dict>
												<key>name</key>
												<string>constant.numeric.decimal.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>("text")</string>
										<key>match</key>
										<string>(?i)\s+("[\($&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w\s]*")</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(text)</string>
										<key>match</key>
										<string>(?i)\s+([\($&amp;%\^/#.,?!;:*+=&lt;&gt;\'\\\-\w]*)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>string</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>$</string>
							</dict>
							<dict>
								<key>comment</key>
								<string>(line|bar) ([)(decimal)+(])</string>
								<key>begin</key>
								<string>(?i)^\s*(line|bar)\s*(\[)</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>comment</key>
										<string>(decimal)</string>
										<key>match</key>
										<string>(?i)\s*([-+]?\d+\.?\d*)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>constant.numeric.decimal.mermaid</string>
											</dict>
										</dict>
									</dict>
									<dict>
										<key>comment</key>
										<string>(,)</string>
										<key>match</key>
										<string>(?i)\s*(,)</string>
										<key>captures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.mermaid</string>
											</dict>
										</dict>
									</dict>
								</array>
								<key>end</key>
								<string>\s*(\])</string>
								<key>endCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>keyword.control.mermaid</string>
									</dict>
								</dict>
							</dict>
						</array>
						<key>end</key>
						<string>(^|\G)(?=\s*[`:~]{3,}\s*$)</string>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>source.mermaid</string>
	</dict>
</plist>